(defun color-theme-sweyla ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/837431/"
  (interactive)
  (color-theme-install
   '(color-theme-sweyla
     ((background-color . "#000001")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))
 
     (font-lock-comment-face ((t (:foreground "#E2D0EB"))))
     (font-lock-constant-face ((t (:foreground "#B12DC3"))))
     (font-lock-builtin-face ((t (:foreground "#FFDD82"))))
     (font-lock-function-name-face ((t (:foreground "#AFB583"))))
     (font-lock-variable-name-face ((t (:foreground "#8D7D82"))))
     (font-lock-keyword-face ((t (:foreground "#647FD5"))))
     (font-lock-string-face ((t (:foreground "#3DC169"))))
     (font-lock-doc-string-face ((t (:foreground "#3DC169"))))
     (font-lock-type-face ((t (:foreground "#F1FF30"))))
     )))
 
(provide 'color-theme-sweyla)
